name: quietheart
description: 'App for children to stay calm and relaxed. It contains a collection of stories, sounds, and videos to help children relax.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter

    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.8
    audioplayers: ^6.1.1
    video_player: ^2.9.2
    fluttertoast: ^8.2.11
    flutter_svg: ^2.0.17
    flutter_native_splash: ^2.4.4
    chewie: ^1.10.0
    dropdown_button2: ^2.3.9
    shared_preferences: ^2.5.2
    google_fonts: ^6.2.1
    flutter_localization: ^0.3.1
    intl: ^0.19.0
    provider: ^6.1.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    generate: true

    assets:
        - assets/images/
        - assets/images/products/
        - assets/images/icons/
        - assets/tales/
        - assets/tales/1/
        - assets/tales/2/
        - assets/tales/3/
        - assets/videos/
        - assets/sounds/

    fonts:
      - family: ShantellSans
        fonts:
          - asset: assets/fonts/ShantellSans-Regular.ttf
            weight: 400
          - asset: assets/fonts/ShantellSans-Italic.ttf
            style: italic
            weight: 400
          - asset: assets/fonts/ShantellSans-Light.ttf
            weight: 300
          - asset: assets/fonts/ShantellSans-LightItalic.ttf
            style: italic
            weight: 300
          - asset: assets/fonts/ShantellSans-Medium.ttf
            weight: 500
          - asset: assets/fonts/ShantellSans-MediumItalic.ttf
            style: italic
            weight: 500
          - asset: assets/fonts/ShantellSans-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/ShantellSans-SemiBoldItalic.ttf
            style: italic
            weight: 600
          - asset: assets/fonts/ShantellSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/ShantellSans-BoldItalic.ttf
            style: italic
            weight: 700
          - asset: assets/fonts/ShantellSans-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/ShantellSans-ExtraBoldItalic.ttf
            style: italic
            weight: 800

    uses-material-design: true