name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload artifact (APK file)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-file
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk-file
          path: downloaded_apk/

      - name: List files in downloaded_apk
        run: ls -R downloaded_apk/

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "downloaded_apk/app-release.apk"
          body: |
            Automatic build from commit ${{ github.sha }}
          name: 'Nightly Build'
          tag: 'nightly-${{ github.run_number }}'
          prerelease: true